DROP TABLE Service cascade constraints PURGE;
DROP SEQUENCE service_seq;
DROP TABLE Debit cascade constraints PURGE;
DROP SEQUENCE debit_seq;
DROP TABLE Payment cascade constraints PURGE;
DROP SEQUENCE payment_seq;
DROP TABLE Call cascade constraints PURGE;
DROP SEQUENCE call_seq;
DROP TABLE Phone_number cascade constraints PURGE;
DROP SEQUENCE phone_number_seq;
DROP TABLE Contract cascade constraints PURGE;
DROP SEQUENCE contract_seq;
DROP TABLE Employee cascade constraints PURGE;
DROP SEQUENCE employee_seq;
DROP TABLE Tariff_plan cascade constraints PURGE;
DROP SEQUENCE tariff_plan_seq;
DROP TABLE Service_description cascade constraints PURGE;
DROP SEQUENCE service_description_seq;
DROP TABLE Client cascade constraints PURGE;
DROP SEQUENCE client_seq;
DROP TABLE Post cascade constraints PURGE;
DROP SEQUENCE post_seq;

DROP TABLE Account_Event cascade constraints PURGE;
DROP SEQUENCE account_event_seq;
DROP TABLE Account cascade constraints PURGE;
